tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "automake"
brew "autopep8"
brew "direnv"
brew "dos2unix"
brew "fish"
brew "fswatch"
brew "gh"
brew "git"
brew "git-vendor"
brew "gnupg"
brew "go"
brew "imagemagick"
brew "jq"
brew "jsonnet"
brew "moreutils"
brew "mosh"
brew "mosquitto"
brew "mpack"
brew "mu"
brew "ninja"
brew "node"
brew "optipng"
brew "pre-commit"
brew "pylint"
brew "ripgrep"
brew "tidy-html5"
brew "tig"
brew "tmux"
brew "w3m"
brew "wget"

# These packages don't currently install on AArch64 macOS:
#
# brew "pandoc"
# brew "mpv"
