.TH DOTFILES 1 "January 2020" "Dotfiles" "Eth's Dotfiles Manual"
.SH NAME
dotfiles \- manage dotfiles using Git
.SH SYNOPSIS
.B dotfiles
.IR cmd
[\fIargs\fR]
.SH DESCRIPTION
A wrapper around
.BR git (1)
that manages dot files in a user's home directory (e.g. ~/.vimrc).
.SH LINKS
https://www.atlassian.com/git/tutorials/dotfiles.
.SH SEE ALSO
.BR dotfiles-init (1),
.BR dotfiles-tig (1),
.BR git (1)
