.TH DOTFILES-INIT 1 "January 2020" "Dotfiles" "Eth's Dotfiles Manual"
.SH NAME
dotfiles-init \- create a new dotfiles repository
.SH SYNOPSIS
.B dotfiles-init
.SH DESCRIPTION
.PP
Initializes a bare Git repository at \fB~/.dotfiles\fR and configures it for
.BR dotfiles (1)
use.
.SH SEE ALSO
.BR dotfiles (1)
