.TH GIT-NEW 1 "January 2020" "Dotfiles" "Eth's Dotfiles Manual"
.SH NAME
git-new \- create a new Git repository and add a blank commit
.SH SYNOPSIS
.B git new
.SH DESCRIPTION
Creates a Git repository using
.BR git-init (1)
then adds a blank commit with the commit message "initial commit".
.SH SEE ALSO
.BR git (1),
.BR git-init (1)
