.TH GIT-HUB 1 "January 2020" "Dotfiles" "Eth's Dotfiles Manual"
.SH NAME
git-hub \- add a Github repository as a remote, and push into it
.SH SYNOPSIS
.B git hub
.I user/repo
.SH DESCRIPTION
From inside an existing Git repository, adds
.B git@github.com:user/repo
as a remote, and pushes the local repository's content into it.
.SH SEE ALSO
.BR git (1)
