.TH PAPERWORK 1 "January 2020" "Dotfiles" "Eth's Dotfiles Manual"
.SH NAME
paperwork \- high-level paperwork utility
.SH SYNOPSIS
.B paperwork
.IR cmd
[\fIargs\fR]
.SH DESCRIPTION
.PP
A high-level paperwork-munging utility.
For example, \fBpaperwork monochrome\fR will convert a JPG to a compressed monochrome PNG for archiving.
.PP
For a full list of what exists, run it with no arguments.
