.TH SERVE-HTTP 1 "January 2020" "Dotfiles" "Eth's Dotfiles Manual"
.SH NAME
serve-http \- serve the current directory over HTTP
.SH SYNOPSIS
.B serve-http
[\fB--port=\fIport\fR]
.SH DESCRIPTION
Serve the current directory over HTTP.
.SH OPTIONS
.TP
.B --port=
The port to listen on.
The default is \fB8080\fR.
